name: Continuous Integration Workflow
on:
  workflow_dispatch:
  push: 
    branches:
      - '*'
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: trigger the automated test in another repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: '${{ secrets.REPO_ACCESS_TOKEN }}'
          repository: DeepShahSDET/QA
          event-type: my-event
          client-payload: '{"github": ${{ toJson(github) }} }'
      - name: my-step
        run: echo "Hello World!"
